kind: ethereum/contract
name: Erc20YeeterShamanTemplate
network:
source:
  abi: Erc20YeeterShaman
mapping:
  kind: ethereum/events
  apiVersion: 0.0.5
  language: wasm/assemblyscript
  file: ./src/yeeter-mapping.ts
  entities:
    - Dao
    - Yeeter
    - Yeets
  abis:
    - name: Erc20YeeterShaman
      file: ./abis/erc20YeeterShaman.json
    - name: Erc20
      file: ./abis/erc20.json
    - name: Erc20Bytes32
      file: ./abis/erc20Bytes32.json
  eventHandlers:
    - event: "OnReceivedERC20(indexed address,uint256,uint256,address,address,string,address)"
      handler: handleOnReceivedERC20
