kind: ethereum/contract
name: YeeterShamanTemplate
network:
source:
  abi: YeeterShaman
mapping:
  kind: ethereum/events
  apiVersion: 0.0.5
  language: wasm/assemblyscript
  file: ./src/yeeter-mapping.ts
  entities:
    - Dao
    - Yeeter
    - Yeets
  abis:
    - name: YeeterShaman
      file: ./abis/yeeterShaman.json
  eventHandlers:
    - event: "OnReceived(indexed address,uint256,uint256,address,address,string)"
      handler: handleOnReceived
